
language: python
python:
    - "2.7"

sudo: false
cache:
    directories:
        - "~/.platformio"

install:
    # - pip install -U platformio
    # Use development version of PlatformIO 3.2 (temporary)
    - pip install -U https://github.com/platformio/platformio/archive/develop.zip


script:
    - echo "Run desktop (native) tests on Travis.CI Linux machine"
    - platformio test -e native　　
